config/routes.rb
Rails.application.routes.draw do

  root "challenges#index"

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :challenges

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/batch.rb
class Batch < ApplicationRecord

  has_many :students, dependent: :destroy
  has_many :challenge_assigments, dependent: :destroy
  has_many :challenges, through: :challenge_assigments

end

app/models/challenge.rb
class Challenge < ApplicationRecord

  has_many :challenge_acceptances, dependent: :destroy
  has_many :students, through: :challenge_acceptances
  has_many :challenge_assignments, dependent: :destroy
  has_many :batchs, through: :challenge_assignments

  validates :score, presence: true,
                    numericality: {
                      only_integer: true,
                      greater_than_or_equal_to: 1,
                      less_than_or_equal_to: 10
                    }
  validates :title, presence: true
  validates :description, presence: true

end

app/models/challenge_acceptance.rb
class ChallengeAcceptance < ApplicationRecord

  belongs_to :challenge
  belongs_to :student

end

app/models/challenge_assignment.rb
class ChallengeAssignment < ApplicationRecord

  belongs_to :batch
  belongs_to :challenge

end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord

  has_many :transactions, dependent: :destroy
  has_many :challenge_acceptances, dependent: :destroy
  has_many :challenges, through: :challenge_acceptances

  belongs_to :batch

end

app/models/transaction.rb
class Transaction < ApplicationRecord

  belongs_to :student
  belongs_to :challenge

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
	before_action :prepare_challenge, only: [:edit, :update, :destroy]

  def index
    @challenges = Challenge.all
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(challenge_params)

    if @challenge.save
      redirect_to challenges_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @challenge.update_attributes(challenge_params)
      redirect_to challenges_path
    else
      render :edit
    end
  end

  def destroy
    @challenge.destroy

    redirect_to challenges_path
  end

  private

	def prepare_challenge
    @challenge = Challenge.find(params[:id])
  end

  def challenge_params
    params.require(:challenge).permit(:title, :description, :score)
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def new
    @user = User.new
  end

  # def create
  #   @user = User.new(sign_up_params)
  #   @user.save
  #   redirect_to challenges_path
  # end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/challenges/_form.html.slim
div class="form container"
	= form_for @challenge do |f|
		div class="form-group"
			= f.label :title, "Title" 
			br
			= f.text_field :title 
		div class="form-group" 
			= f.label :description, "Description"
			br 
			= f.text_area :description
		div class="form-group"	
			= f.label :score, "Score (1-10, integer only)"
			br
			= f.text_field :score

		= f.submit

app/views/challenges/edit.html.slim
- if @challenge.errors.present?
  ul
    - @challenge.errors.each do |error, message| 
      li
        = "#{error.capitalize}  #{message}"
  

= render :partial => "form" 

app/views/challenges/index.html.slim
table class="table"
	thead
		tr 
			th Title
			th Description
			th Score
	- @challenges.each do |challenge|	
		tbody
			tr 
				td 
					= challenge.title
				td 
					= challenge.description
				td 
					= challenge.score
				td 
					= link_to	"Edit", edit_challenge_path(challenge)
				td 
				 	= link_to "Delete", challenge_path(challenge), method: :delete, data: {confirm: 'Are you sure?'}

= link_to "New challenge", new_challenge_path	

app/views/challenges/new.html.slim
- if @challenge.errors.present?
  ul
    - @challenge.errors.each do |error, message|
      li 
        = "#{error.capitalize}  #{message}"

= render :partial => "form"

app/views/layouts/application.html.slim
html
head
  title SquirrelRailsV1
  = csrf_meta_tags

  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

body
  - if current_user
    = link_to('sign out', destroy_user_session_path, method: :delete)
    br
    = link_to('change password', edit_registration_path(current_user))
  - else
    = link_to('sign up', new_user_registration_path) 
    br
    = link_to('sign in', new_user_session_path)

  p.notice = notice
	p.alert = alert
  
  = yield

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>